#!/usr/bin/env bash
# This script provides answers to MAC and IP address questions

# Question 1
echo "What is a MAC address?"
echo "Answer: The unique identifier of a network interface"
echo ""

# Question 2
echo "What is an IP address?"
echo "Answer: Is to devices connected to a network what postal address is to houses"
echo ""

