#!/usr/bin/env bash

# This Bash script displays a list of currently running processes, including process hierarchy, in a user-oriented format.

# Using the 'ps' command to get process information and displaying only necessary columns in a user-oriented format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | head -n 50
