#!/usr/bin/env bash

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Send SIGTERM signal to the process to request termination
if [ -n "$pid" ]; then
  kill -SIGTERM "$pid"
fi
