#!/usr/bin/env bash

# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Send SIGTERM signal to the process to request termination
if [ -n "$pid" ]; then
  kill -SIGTERM "$pid"
fi

