#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Counter variable
count=0

# Until loop to display "Best School" 10 times
until [ $count -ge 10 ]; do
    echo "Best School"
    ((count++))
done
