#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Loop to display hours from 0 to 12
hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    # Loop to display minutes from 1 to 59
    minute=1
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
        
        # Add a condition to exit the minute loop after printing the first 60 lines (1 to 59)
        if [ $minute -eq 60 ]; then
            break
        fi
    done

    ((hour++))
done
