#!/usr/bin/env bash

# Bash script that configures an Ubuntu server with the below requirements.

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Create a new hosts file with the required configurations
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original hosts file with the new configuration
sudo cp -f ~/hosts.new /etc/hosts

# Clean up
rm ~/hosts.new

