#!/usr/bin/env bash
# This Bash script configures an Ubuntu server as per the specified criteria.

# Create a backup of the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Replace the IP address 127.0.0.1 with 127.0.0.2 in the new hosts file
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Add an entry to map facebook.com to the IP address 8.8.8.8 in the new hosts file
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the system's /etc/hosts file with the modified version
cp -f ~/hosts.new /etc/hosts

# Clean up by removing the temporary hosts.new file
rm ~/hosts.new
