#!/usr/bin/env bash

# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Use 'ifconfig' command to retrieve network interface information,
# 'grep' to filter lines containing 'inet' followed by an IPv4 address pattern,
# and 'awk' to extract the IPv4 address part.
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
