#!/usr/bin/env bash

# Get all active IPv4 IPs using ifconfig
active_ips=$(ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | cut -d' ' -f2)

# Display the active IPs
echo "$active_ips"
