#!/usr/bin/env bash

# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Use 'ifconfig' to retrieve network interface information, 'grep' to filter lines containing 'inet ',
# and 'awk' to extract the IP address.
ipv4_addresses=$(ifconfig | grep 'inet ' | awk '{print $2}' | cut -d':' -f2)

# Display the list of active IPv4 addresses.
echo "$ipv4_addresses"

