#!/usr/bin/env bash

# Change Nginx user in the configuration
sed -i 's/user  www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change the default site configuration to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Remove the default symbolic link in sites-enabled
rm -f /etc/nginx/sites-enabled/default

# Create a symbolic link to enable the default site configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
nginx -t
service nginx reload

# Verify Nginx is running as the nginx user
ps aux | grep 'nginx:'
