#!/usr/bin/env bash

# Modify Nginx configuration
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Change ownership to nginx user and group for the Nginx configuration file
chown nginx:nginx /etc/nginx/nginx.conf

# Set file permissions to 755 for the Nginx configuration file
chmod 755 /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart
