#!/usr/bin/env bash

# Replace 'apache2' with 'nginx' in the default Nginx configuration
sed -i 's/apache2/nginx/g' /etc/nginx/sites-available/default

# Reload Nginx configuration to apply changes
service nginx reload
