#!/usr/bin/env bash
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
echo -e "server {\n\tlisten 8080;\n\tserver_name _;\n\n\tlocation / {\n\t\troot /usr/share/nginx/html;\n\t\tindex index.html;\n\t}\n}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx -t
service nginx restart
